# **Important Libraries**

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# **Load and Preprocess the dataset**

In [2]:
df = pd.read_csv("/kaggle/input/f1-spam-detection/train.csv")
df.head()

message_id  num_links  num_words  has_offer  sender_score  all_caps  \
0           1          3         98          1      0.718607         0   
1           2          0        170          0      0.698901         1   
2           3          0         38          0      0.620466         0   
3           4          0        116          0      0.701755         0   
4           5          3         89          1      0.583621         1   

   is_spam  
0        0  
1        0  
2        0  
3        0  
4        1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19100 entries, 0 to 19099
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   message_id    19100 non-null  int64  
 1   num_links     19100 non-null  int64  
 2   num_words     19100 non-null  int64  
 3   has_offer     19100 non-null  int64  
 4   sender_score  19100 non-null  float64
 5   all_caps      19100 non-null  int64  
 6   is_spam       19100 non-null  int64  
dtypes: float64(1), int64(6)
memory usage: 1.0 MB


In [4]:
# Check for null values
df.isna().sum()

message_id      0
num_links       0
num_words       0
has_offer       0
sender_score    0
all_caps        0
is_spam         0
dtype: int64

In [5]:
# Check for duplicates
df.duplicated().sum()

0

In [6]:
df['is_spam'].value_counts() # Dataset is imbalanced

is_spam
0    17354
1     1746
Name: count, dtype: int64

In [7]:
# Drop unnecessary columns
df.drop(['message_id'], axis=1,inplace=True)

In [8]:
# Feature Engineering
df['links_per_word'] = df['num_links'] / (df['num_words'] + 1)
df.head()

num_links  num_words  has_offer  sender_score  all_caps  is_spam  \
0          3         98          1      0.718607         0        0   
1          0        170          0      0.698901         1        0   
2          0         38          0      0.620466         0        0   
3          0        116          0      0.701755         0        0   
4          3         89          1      0.583621         1        1   

   links_per_word  
0        0.030303  
1        0.000000  
2        0.000000  
3        0.000000  
4        0.033333

In [9]:
df.describe()

num_links     num_words     has_offer  sender_score      all_caps  \
count  19100.000000  19100.000000  19100.000000  19100.000000  19100.000000   
mean       1.498272    109.651780      0.303298      0.694174      0.097853   
std        1.221115     51.974463      0.459695      0.188285      0.297124   
min        0.000000     20.000000      0.000000      0.000000      0.000000   
25%        1.000000     65.000000      0.000000      0.566990      0.000000   
50%        1.000000    110.000000      0.000000      0.699204      0.000000   
75%        2.000000    155.000000      1.000000      0.834200      0.000000   
max        9.000000    199.000000      1.000000      1.000000      1.000000   

            is_spam  links_per_word  
count  19100.000000    19100.000000  
mean       0.091414        0.018992  
std        0.288204        0.023753  
min        0.000000        0.000000  
25%        0.000000        0.005435  
50%        0.000000        0.012346  
75%        0.000000        0.024390  
max        1.000000        0.318182

In [10]:
df.corr()

num_links  num_words  has_offer  sender_score  all_caps  \
num_links        1.000000   0.003194  -0.004057     -0.002424  0.000682   
num_words        0.003194   1.000000  -0.005518      0.004276  0.001451   
has_offer       -0.004057  -0.005518   1.000000     -0.002169 -0.001098   
sender_score    -0.002424   0.004276  -0.002169      1.000000  0.018184   
all_caps         0.000682   0.001451  -0.001098      0.018184  1.000000   
is_spam          0.322846   0.000849   0.368503     -0.088210  0.207979   
links_per_word   0.657699  -0.488613  -0.006697     -0.007697 -0.002816   

                 is_spam  links_per_word  
num_links       0.322846        0.657699  
num_words       0.000849       -0.488613  
has_offer       0.368503       -0.006697  
sender_score   -0.088210       -0.007697  
all_caps        0.207979       -0.002816  
is_spam         1.000000        0.210271  
links_per_word  0.210271        1.000000

In [11]:
X = df.drop(['is_spam'], axis=1).values
y = df['is_spam'].values

In [12]:
X

array([[3.00000000e+00, 9.80000000e+01, 1.00000000e+00, 7.18607000e-01,
        0.00000000e+00, 3.03030303e-02],
       [0.00000000e+00, 1.70000000e+02, 0.00000000e+00, 6.98901226e-01,
        1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 3.80000000e+01, 0.00000000e+00, 6.20465534e-01,
        0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 1.45000000e+02, 0.00000000e+00, 6.00568655e-01,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.78000000e+02, 0.00000000e+00, 6.75468409e-01,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 8.00000000e+01, 0.00000000e+00, 6.97732338e-01,
        0.00000000e+00, 0.00000000e+00]])

In [13]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [14]:
# Stratified train-validation split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [15]:
# Verify stratification
print("Training set class distribution:", np.bincount(y_train))
print("Validation set class distribution:", np.bincount(y_val))

Training set class distribution: [13883  1397]
Validation set class distribution: [3471  349]


In [16]:
scaler = scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

# **Logistic Regression**

In [17]:
class LogisticRegression:
    def __init__(self, learning_rate=0.01, max_iterations=1000, lambda_reg=0.1,
                 reg_type='l2', class_weight=None, batch_size=32, shuffle=True):
        # Hyperparameters
        self.learning_rate = learning_rate
        self.max_iterations = max_iterations
        self.lambda_reg = lambda_reg
        self.reg_type = reg_type.lower()
        self.class_weight = class_weight  # None, 'balanced', or dict
        self.batch_size = batch_size      # Mini-batch size
        self.shuffle = shuffle            # Shuffle data each epoch

        # Model parameters
        self.weights = None
        self.bias = None

    def sigmoid(self, z):
        """Sigmoid activation with clipping to avoid overflow."""
        z = np.clip(z, -500, 500)
        return 1 / (1 + np.exp(-z))

    def log_loss(self, y_true, y_pred):
        """Binary cross-entropy loss with regularization."""
        epsilon = 1e-15
        y_pred = np.clip(y_pred, epsilon, 1 - epsilon)  # Avoid log(0)
        loss = -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

        # Add regularization penalty
        if self.reg_type == 'l1':
            reg_term = self.lambda_reg * np.sum(np.abs(self.weights))
        elif self.reg_type == 'l2':
            reg_term = self.lambda_reg * np.sum(self.weights ** 2) / 2
        else:
            raise ValueError("reg_type must be 'l1' or 'l2'")

        return loss + reg_term

    def _compute_sample_weights(self, y):
        """Convert class_weight into a weight for each sample."""
        if self.class_weight == 'balanced':
            # Weight inversely proportional to class frequency
            classes, counts = np.unique(y, return_counts=True)
            total = len(y)
            weight_dict = {cls: total / (2 * count) for cls, count in zip(classes, counts)}
            return np.array([weight_dict[label] for label in y])

        elif isinstance(self.class_weight, dict):
            # Manual class weights
            return np.array([self.class_weight[label] for label in y])

        else:
            # No weighting
            return np.ones_like(y)

    def fit(self, X, y):
        """Train the logistic regression model using mini-batch gradient descent."""
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        sample_weights = self._compute_sample_weights(y)

        for _ in range(self.max_iterations):
            # Shuffle data each epoch if enabled
            if self.shuffle:
                indices = np.arange(n_samples)
                np.random.shuffle(indices)
                X = X[indices]
                y = y[indices]
                sample_weights = sample_weights[indices]

            # Process each mini-batch
            for start in range(0, n_samples, self.batch_size):
                end = start + self.batch_size
                X_batch = X[start:end]
                y_batch = y[start:end]
                sw_batch = sample_weights[start:end]

                # Forward pass
                linear_model = np.dot(X_batch, self.weights) + self.bias
                y_pred = self.sigmoid(linear_model)

                # Compute weighted error
                error = y_pred - y_batch
                weighted_error = error * sw_batch

                # Regularization gradient
                if self.reg_type == 'l1':
                    reg_grad = self.lambda_reg * np.sign(self.weights)
                elif self.reg_type == 'l2':
                    reg_grad = self.lambda_reg * self.weights
                else:
                    raise ValueError("reg_type must be 'l1' or 'l2'")

                # Gradients
                dw = (1 / len(X_batch)) * np.dot(X_batch.T, weighted_error) + (reg_grad / n_samples)
                db = (1 / len(X_batch)) * np.sum(weighted_error)

                # Parameter update
                self.weights -= self.learning_rate * dw
                self.bias -= self.learning_rate * db

    def predict_proba(self, X):
        """Predict probabilities for input samples."""
        return self.sigmoid(np.dot(X, self.weights) + self.bias)

    def predict(self, X, threshold=0.5):
        """Predict binary class labels based on a threshold."""
        return (self.predict_proba(X) >= threshold).astype(int)

In [18]:
def grid_search(X_train, y_train, X_val, y_val, param_grid):
    best_log_loss = float('inf')
    best_params = None
    best_model = None

    # Try every combination of parameters
    for lr in param_grid['learning_rate']:
        for lam in param_grid['lambda_reg']:
            for max_iter in param_grid['max_iterations']:
                for reg_type in param_grid['reg_type']:
                    for class_weight in param_grid['class_weights']:
                        for batch_size in param_grid['batch_size']:

                            # Create model with given hyperparameters
                            model = LogisticRegression(
                                learning_rate=lr,
                                max_iterations=max_iter,
                                lambda_reg=lam,
                                reg_type=reg_type,
                                class_weight=class_weight,
                                batch_size=batch_size
                            )

                            # Train model
                            model.fit(X_train, y_train)

                            # Evaluate on validation set
                            y_pred_proba = model.predict_proba(X_val)
                            log_loss_val = model.log_loss(y_val, y_pred_proba)

                            # Print current combination results
                            print(f"LR: {lr}, Lambda: {lam}, MaxIter: {max_iter}, "
                                  f"Reg: {reg_type}, Class Weight: {class_weight}, "
                                  f"Batch: {batch_size}, LogLoss: {log_loss_val:.4f}")

                            # Track best model
                            if log_loss_val < best_log_loss:
                                best_log_loss = log_loss_val
                                best_params = {
                                    'learning_rate': lr,
                                    'lambda_reg': lam,
                                    'max_iterations': max_iter,
                                    'reg_type': reg_type,
                                    'class_weight': class_weight,
                                    'batch_size': batch_size
                                }
                                best_model = model

    return best_model, best_params, best_log_loss

In [ ]:
param_grid = {
    'learning_rate': [ 0.05, 0.01, 0.1,0.2],
    'lambda_reg': [ 0.0001, 0.001, 0.01],
    'max_iterations': [4000, 5000, 6000],
    'reg_type': ['L1','L2'],
    'class_weights': [ None, 'balanced', {0: 3, 1: 6}],
    'batch_size': [1,16, 32]
}

best_model, best_params, best_log_loss = grid_search(
    X_train_scaled, y_train, X_val_scaled, y_val, param_grid
)

print("\n Best Parameters:", best_params)
print(f" Best Validation LogLoss: {best_log_loss:.4f}")

In [19]:
# From previous notebook
best_parameters = {'learning_rate': 0.05, 'lambda_reg': 0.0001, 'max_iterations': 6000, 'reg_type': 'L2', 'class_weight': None}
 

In [19]:
model_8 = LogisticRegression(
    learning_rate= 0.05,
    lambda_reg= 0.0001,
    max_iterations= 6000,
    reg_type= 'L2',
    class_weight= None,
    batch_size=8
) 

model_8.fit(X_train_scaled, y_train)

y_val_pred_8 = model_8.predict_proba(X_val_scaled)
log_loss_8 = model_8.log_loss(y_val, y_val_pred_8)

print(f"Log Loss:  {log_loss_8:.4f}")

Log Loss:  0.1622


In [20]:
model_16 = LogisticRegression(
    learning_rate= 0.05,
    lambda_reg= 0.0001,
    max_iterations= 6000,
    reg_type= 'L2',
    class_weight= None,
    batch_size=16
) 

model_16.fit(X_train_scaled, y_train)

y_val_pred_16 = model_16.predict_proba(X_val_scaled)
log_loss_16 = model_16.log_loss(y_val, y_val_pred_16)

print(f"Log Loss:  {log_loss_16:.4f}")

Log Loss:  0.1635


In [21]:
model_32 = LogisticRegression(
    learning_rate= 0.05,
    lambda_reg= 0.0001,
    max_iterations= 6000,
    reg_type= 'L2',
    class_weight= None,
    batch_size=32
) 

model_32.fit(X_train_scaled, y_train)

y_val_pred_32 = model_32.predict_proba(X_val_scaled)
log_loss_32 = model_32.log_loss(y_val, y_val_pred_32)

print(f"Log Loss:  {log_loss_32:.4f}")

Log Loss:  0.1620


In [22]:
model_64 = LogisticRegression(
    learning_rate= 0.05,
    lambda_reg= 0.0001,
    max_iterations= 6000,
    reg_type= 'L2',
    class_weight= None,
    batch_size=64
) 

model_64.fit(X_train_scaled, y_train)

y_val_pred_64 = model_64.predict_proba(X_val_scaled)
log_loss_64 = model_64.log_loss(y_val, y_val_pred_64)

print(f"Log Loss:  {log_loss_64:.4f}")

Log Loss:  0.1619


In [23]:
model_128 = LogisticRegression(
    learning_rate= 0.05,
    lambda_reg= 0.0001,
    max_iterations= 6000,
    reg_type= 'L2',
    class_weight= None,
    batch_size=128
)

model_128.fit(X_train_scaled, y_train)

y_val_pred_128 = model_128.predict_proba(X_val_scaled)
log_loss_128 = model_128.log_loss(y_val, y_val_pred_128)

print(f"Log Loss:  {log_loss_128:.4f}")

Log Loss:  0.1618


In [24]:
model_sgd = LogisticRegression(
    learning_rate= 0.05,
    lambda_reg= 0.0001,
    max_iterations= 6000,
    reg_type= 'L2',
    class_weight= None,
    batch_size=1
)

model_sgd.fit(X_train_scaled, y_train)

y_val_pred_sgd = model_sgd.predict_proba(X_val_scaled)
log_loss_sgd = model_sgd.log_loss(y_val, y_val_pred_sgd)

print(f"Log Loss:  {log_loss_sgd:.4f}")

Log Loss:  0.1800


In [29]:
test = pd.read_csv("/kaggle/input/f1-spam-detection/test.csv")
test.head()

message_id  num_links  num_words  has_offer  sender_score  all_caps
0       20000          1         37          0      0.633935         0
1       20001          0        174          0      0.577815         0
2       20002          0        116          0      0.396098         0
3       20003          0        112          0      0.646450         0
4       20004          2         92          1      0.947398         1

In [30]:
features = test.drop(['message_id'],axis=1)
ids = test['message_id']
ids

0      20000
1      20001
2      20002
3      20003
4      20004
       ...  
895    20895
896    20896
897    20897
898    20898
899    20899
Name: message_id, Length: 900, dtype: int64

In [31]:
features['links_per_word'] = features['num_links'] / (features['num_words'] + 1)

In [32]:
features_scaled = scaler.transform(features)

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [33]:
features_scaled

array([[-0.40651901, -1.40094477, -0.65955384, -0.32096753, -0.33078237,
         0.31583616],
       [-1.22512872,  1.23959789, -0.65955384, -0.62052284, -0.33078237,
        -0.80432018],
       [-1.22512872,  0.12170392, -0.65955384, -1.59048397, -0.33078237,
        -0.80432018],
       ...,
       [-0.40651901,  0.73847301,  1.51617645,  0.26417161, -0.33078237,
        -0.51864273],
       [ 0.4120907 ,  1.23959789, -0.65955384, -0.60219107,  3.02313574,
        -0.31785228],
       [ 0.4120907 , -0.398695  , -0.65955384,  1.37254115, -0.33078237,
         0.14158962]])

In [34]:
predictions = model_128.predict_proba(features_scaled)
predictions

array([1.08739758e-03, 3.21745257e-04, 5.48367045e-04, 2.61390859e-04,
       7.64395157e-01, 3.52241147e-04, 6.80061416e-04, 2.23555901e-03,
       1.59169230e-02, 4.99768384e-03, 1.77782079e-04, 4.53223088e-02,
       3.77546111e-03, 3.06784798e-03, 1.69826370e-02, 3.65416848e-03,
       4.64259699e-01, 2.71374588e-03, 2.49897030e-03, 9.73243347e-04,
       1.01461258e-03, 1.67108920e-02, 5.22388170e-01, 1.86668257e-02,
       6.58128050e-02, 1.97587684e-04, 3.69344433e-02, 1.28914462e-01,
       5.49592753e-01, 6.90425169e-03, 2.33056940e-03, 2.62295460e-04,
       1.27980011e-02, 4.09818197e-03, 8.35213590e-04, 7.56870833e-01,
       1.97345314e-04, 5.31795233e-03, 1.86023533e-03, 1.69475869e-04,
       1.90050382e-02, 1.00608379e-03, 9.17746605e-05, 2.39123453e-04,
       9.37601341e-01, 6.89552163e-03, 8.24955881e-01, 3.35100165e-02,
       2.96670082e-04, 6.77742763e-03, 8.95777574e-04, 1.81791879e-01,
       1.64890285e-04, 2.42800041e-03, 1.84049314e-04, 4.55060561e-02,
      

In [35]:
submission = pd.DataFrame({
    'message_id': ids,
    'Calories': predictions
})
submission.head()

message_id  Calories
0       20000  0.001087
1       20001  0.000322
2       20002  0.000548
3       20003  0.000261
4       20004  0.764395

In [36]:
submission.to_csv('submission.csv', index=False)